# Generated by Django 4.2 on 2023-04-07 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyevents',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 7, 22, 13, 51, 123757, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
