# Generated by Django 4.2 on 2023-04-07 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracking', '0002_studyevents_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyevents',
            name='date',
        ),
        migrations.AddField(
            model_name='studyevents',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studyevents',
            name='photos',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
