# Generated by Django 4.2 on 2023-04-10 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracking', '0006_alter_studentestimates_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentestimates',
            name='date',
        ),
        migrations.RemoveField(
            model_name='studentestimates',
            name='subject_ID',
        ),
        migrations.CreateModel(
            name='SubjectLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('topic', models.CharField(max_length=255, null=True, verbose_name='Тема')),
                ('subject_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress_tracking.subjects', verbose_name='Предмет')),
            ],
        ),
        migrations.AddField(
            model_name='studentestimates',
            name='lesson_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='progress_tracking.subjectlessons'),
            preserve_default=False,
        ),
    ]
