# Generated by Django 4.2 on 2023-04-10 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracking', '0007_remove_studentestimates_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentestimates',
            name='lesson_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress_tracking.subjectlessons'),
        ),
    ]
