# Generated by Django 4.2 on 2023-04-10 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracking', '0008_alter_studentestimates_lesson_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentestimates',
            name='mark',
            field=models.CharField(choices=[('1', 'Poor'), ('2', 'Unsatisfactory'), ('3', 'Satisfactory'), ('4', 'Good'), ('5', 'Excellent'), ('n', 'Absent')], max_length=1),
        ),
        migrations.AlterField(
            model_name='subjectlessons',
            name='subject_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress_tracking.groupsubjects', verbose_name='Предмет'),
        ),
    ]
